# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReqeustMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
                ('msg_type', models.CharField(max_length=32)),
                ('msg_src', models.CharField(max_length=64)),
                ('msg_data', models.CharField(max_length=1024)),
                ('msg_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
                ('msg_type', models.CharField(max_length=32)),
                ('msg_dst', models.CharField(max_length=64)),
                ('msg_data', models.CharField(max_length=1024)),
                ('msg_url', models.CharField(max_length=128)),
            ],
        ),
    ]
