# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReqeustMessage',
            new_name='RequestMessage',
        ),
    ]
